apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-uhmgrxss
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-uhmgrxss:68babf81cee14cf0944ada8540710a83c0afa99a@sha256:c89a5010dfa191ed91cc15b4b5257d40e380ad45d6179da4719bdacd96d107da
          name: container-image
